<?php
include_once 'SpeedTaxApi.php';
include_once 'SpeedTaxUtil.php';

print "Enter a customer reference, e.g. one generated by CreateEditCustomer.php\n\n";	
print "Reference...: ";
$f = fopen('php://stdin', 'r');
$Ref = trim(fgets($f));
print "\n";
	
print "Creating exemption\n";

// ****************
// Create Exemption
// ****************
try 
{
	$ExemptionCertificate = new exemptionCertificate();
	$ExemptionCertificate->customerReference = $Ref; 
	$ExemptionCertificate->exemptionReference = "EXREF12345";
	$ExemptionCertificate->startDate = "2010-01-01";
	$ExemptionCertificate->endDate = "2015-01-01";
    $ExemptionCertificate->reasonForExemption = "Retail";
    $ExemptionCertificate->rateOfExemption = 0.42; // 1.0 = 100% exemption, 0.0 = no exemption
    $ExemptionCertificate->exemptedStateCodes = array("CA", "FL");
    // $ExemptionCertificate->skuCode = "10000000";  // Uncomment line to make specific to a taxability code
	
    //print_r($ExemptionCertificate);
    //die("Trying");
    
	// Call the web service
	
	$stx = new SpeedTax();
	
	print "Create Exemption:" . "\n";
	$result = $stx->CreateExemption($ExemptionCertificate);

	switch ($result->CreateExemption->resultType)
	{	
		case 'CREATED':
			print "CREATED.\n";
			break;
		case 'UPDATED':
			print "UPDATED.\n";
			break;
		case 'FAILED_WITH_ERRORS':
			print "FAILED.  Errors:\n";
			DisplayErrors($result->CreateExemption->errors);
			break;
		default:
			print "Other result type: '" . $result->CreateExemption->resultType . "'\n";
			break;
	}	
}
catch (Exception $e) 
{
    // in case of an error, process the fault
    if ($e instanceof WSFault) 
    {
        printf("Soap Fault: %s\n", $e->Reason);
    } 
    else 
    {
        printf("Exception Message = %s\n", $e->getMessage());
    }
}

print "Verify that the exemption was created, then press ENTER to update...";	
$f = fopen('php://stdin', 'r');
$line = fgets($f);
print "\n";


// ****************
// Update Exemption
// ****************
try 
{
	$ExemptionCertificate = new exemptionCertificate();	
	$ExemptionCertificate->customerReference = $Ref; 
	$ExemptionCertificate->exemptionReference = "EXREF12345";
	$ExemptionCertificate->startDate = "2010-01-01";
	$ExemptionCertificate->endDate = "2042-01-01";
    $ExemptionCertificate->reasonForExemption = "Government";
    $ExemptionCertificate->rateOfExemption = 0.42; // 1.0 = 100% exemption, 0.0 = no exemption
    $ExemptionCertificate->exemptedStateCodes = array("CA", "FL");
    // $ExemptionCertificate->skuCode = "10000000";  // Uncomment line to make specific to a taxability code
	    
	// Call the web service
	
	$stx = new SpeedTax();
	
	print "Update Exemption:" . "\n";
	$result = $stx->EditExemption($ExemptionCertificate);

	switch ($result->EditExemption->resultType)
	{	
		case 'CREATED':
			print "CREATED.\n";
			break;
		case 'UPDATED':
			print "UPDATED.\n";
			break;
		case 'FAILED_WITH_ERRORS':
			print "FAILED.  Errors:\n";
			DisplayErrors($result->EditExemption->errors);
			break;
		default:
			print "Other result type: '" . $result->EditExemption->resultType . "'\n";
			break;
	}	
}
catch (Exception $e) 
{
    // in case of an error, process the fault
    if ($e instanceof WSFault) 
    {
        printf("Soap Fault: %s\n", $e->Reason);
    } 
    else 
    {
        printf("Exception Message = %s\n", $e->getMessage());
    }
}

?>

