<?
	$db->Execute(
		$sql = sprintf("
			UPDATE
				shop_sessions
			SET
				billing_name=%s
				,billing_email=%s
				,billing_phone=%s
				,billing_line1=%s
				,billing_line2=%s
				,billing_line3=%s
				,billing_line4=%s
				,billing_postcode=%s
				,billing_state=%s
				,billing_country_id=%u
				,billing_country=%s
				,cvv=%s
				,delivery_name=%s
				,delivery_email=%s
				,delivery_phone=%s
				,delivery_line1=%s
				,delivery_line2=%s
				,delivery_line3=%s
				,delivery_line4=%s
				,delivery_postcode=%s
				,delivery_country_id=%u
				,additional_payment=%u
				,customerProfileId=%s
				,customerAddressId=%s
				,paymentProfileId=%s
				,delivery_speedtax_status = 'FULL'
			WHERE
				session_id=%s
		"
			,$db->Quote(safe($_REQUEST['billing_name']))
			,$db->Quote(safe($_REQUEST['billing_email']))
			,$db->Quote(safe($_REQUEST['billing_phone']))
			,$db->Quote(safe($_REQUEST['billing_line1']))
			,$db->Quote(safe($_REQUEST['billing_line2']))
			,$db->Quote(safe($_REQUEST['billing_line3']))
			,$db->Quote(safe($_REQUEST['billing_line4']))
			,$db->Quote(safe($_REQUEST['billing_postcode']))
			,$db->Quote(safe($_REQUEST['billing_state']))
			,safe($_REQUEST['billing_country_id'])
			,$db->Quote(safe($_REQUEST['billing_country']))
			,$db->Quote(safe($_REQUEST['cvv']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_name']:$_REQUEST['delivery_name']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_email']:$_REQUEST['delivery_email']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_phone']:$_REQUEST['delivery_phone']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_line1']:$_REQUEST['delivery_line1']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_line2']:$_REQUEST['delivery_line2']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_line3']:$_REQUEST['delivery_line3']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_line4']:$_REQUEST['delivery_line4']))
			,$db->Quote(safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_postcode']:$_REQUEST['delivery_postcode']))
			,safe(($_REQUEST['same_billing']+0)?$_REQUEST['billing_country_id']:$_REQUEST['delivery_country_id'])
			,$_REQUEST['additional_payment']?1:0
			,$db->Quote(safe($user_session->session->fields['authorize_profile_id']))
			,$db->Quote(safe($_REQUEST['customerAddressId']))
			,$db->Quote(safe($_REQUEST['paymentProfileId']))
			,$db->Quote($session->session_id)
		)
	);
?>
