<?
	$db->SetTransactionMode("SERIALIZABLE");
	$db->StartTrans();
	
	if($_POST['dir']=="up")
	{
		$ord=$db->Execute(
			sprintf("
				SELECT
					ord
				FROM
					shop_products
				WHERE
					id=%u
			"
				,$_POST['product_id']
			)
		);
		if($ord->fields['ord']>0)
		{
			$db->Execute(
				sprintf("
					UPDATE
						shop_products
					SET
						ord=ord+1
					WHERE
						ord=%u
					AND
						category_id=%u
				"
					,$ord->fields['ord']-1
					,$_POST['category_id']
				)
			);
			$db->Execute(
				sprintf("
					UPDATE
						shop_products
					SET
						ord=ord-1
					WHERE
						id=%u
				"
					,$_POST['product_id']
				)
			);
		}
	}
	else
	{
		$ord=$db->Execute(
			sprintf("
				SELECT
					ord
				FROM
					shop_products
				WHERE
					id=%u
			"
				,$_POST['product_id']
			)
		);
		$max=$db->Execute(
			sprintf("
				SELECT
					MAX(ord) AS max
				FROM
					shop_products
				WHERE
					category_id=%u
			"
				,$_POST['category_id']
			)
		);
		if($ord->fields['ord']<$max->fields['max'])
		{
			$db->Execute(
				sprintf("
					UPDATE
						shop_products
					SET
						ord=ord-1
					WHERE
						ord=%u
					AND
						category_id=%u
				"
					,$ord->fields['ord']+1
					,$_POST['category_id']
				)
			);
			$db->Execute(
				sprintf("
					UPDATE
						shop_products
					SET
						ord=ord+1
					WHERE
						id=%u
				"
					,$_POST['product_id']
				)
			);
		}
	}
	
	$ok=$db->CompleteTrans();
	if(!$ok)
    	error("There was a problem whilst ordering the product, please try again.  If this persists please notify your designated support contact","Database Error");
?>
